manifest:
  remotes:
    - name: zmkfirmware
      url-base: https://github.com/zmkfirmware
    - name: packorf
      url-base: https://github.com/packorf
    - name: 
  projects:
    - name: zmk
      remote: packorf
      revision: features/soft-off-take-2
      import: app/west.yml
  self:
    path: config
